title: scipiper tips and tricks
description: Common issues and approaches for debugging scipiper pipelines
template:
  name: ds-pipelines-2-template
  repo: ds-pipelines-2
before:
  - type: createIssue
    title: Overview of data science pipelines II
    body: 00-overview.md
    store:
      overview_issue_url: '{{ result.data.html_url }}'
steps:
  - title: Overview of data science pipelines II
    description: A refresher from pipelines I, and a hint of what is to come
    link: '{{ store.overview_issue_url }}'
    event: issues.closed
    actions:
      - type: respond
        with: zz-goto-next-issue.md
      - type: createIssue
        title: Strategies for defining targets in data pipelines
        body: 10-many-targets.md
        store:
          many_targets_url: '{{ result.data.html_url }}'
          many_targets_id: '{{ result.data.number }}'
  - title: Strategies for defining targets in data pipelines
    description: >-
      Sometimes it is hard to figure out when something should be a tracked target vs an internal step of a longer-running function
    link: '{{ store.many_targets_url }}'
    event: issues.assigned
    actions:
      - type: respond
        with: 11-target-expense.md
        store:
          target_expense_url: '{{ result.data.html_url }}'
  - title: Determining when to create a new target or merge existing targets
    description: Existing project examples that use pipelines; strategies for defining targets based on computational expense and re-use
    link: '{{ store.target_expense_url }}'
    event: issues.closed
    actions:
      - type: respond
        with: zz-goto-next-issue.md
      - type: createIssue
        title: Refactor the existing pipeline to use more effective targets
        body: 12-target-refactor.md
        store:
          target_refactor_url: '{{ result.data.html_url }}'
          target_refactor_id: '{{ result.data.number }}'

  - title: Learn how to refactor an existing pipeline to use more effective targets
    description: A hands-on activity designed to expose the learner to decisions with targets
    link: '{{ store.target_refactor_url }}'
    event: pull_request.closed
    actions:
      - type: respond
        with: zz-goto-next-issue.md
      - type: createIssue
        title: Learn the differences between different types of targets
        body: 20-target-kinds.md
        store:
          target_kinds_url: '{{ result.data.html_url }}'
          target_kinds_id: '{{ result.data.number }}'
      - type: closeIssue
        issue: '{{ store.target_refactor_id }}'
  - title: Object vs file targets
    description: Overview of different types of targets
    link: '{{ store.target_kinds_url }}'
    event: issues.assigned
    actions:
      - type: respond
        with: 21-object-targets.md
        store:
          object_targets_url: '{{ result.data.html_url }}'
  - title: When to use object targets vs file targets
    description: How to choose between files and R objects for pipeline targets
    link: '{{ store.object_targets_url }}'
    event: issue_comment.created
    actions:
      - type: respond
        with: 22-file-targets.md
        store:
          file_targets_url: '{{ result.data.html_url }}'          
  - title: file targets
    description: file targets in pipelines
    link: '{{ store.file_targets_url }}'
    event: issues.closed
    actions:
      - type: respond
        with: zz-goto-next-issue.md
      - type: createIssue
        title: Exchange object and file targets in your pipelines
        body: 23-target-activity.md
        store:
          target_switch_url: '{{ result.data.html_url }}'
          target_switch_id: '{{ result.data.number }}'

# -- section 30 --- 
  - title: Exchange object and file targets in your pipelines
    link: '{{ store.target_switch_url }}'
    event: pull_request.closed
    actions:
      - type: respond
        with: zz-goto-next-issue.md
      - type: createIssue
        title: How to get past the gotchas without getting gotten again
        body: 30-scipiper-gotchas.md
        store:
          scipiper_gotchyas_url: '{{ result.data.html_url }}'
          scipiper_gotchyas_id: '{{ result.data.number }}'
      - type: closeIssue
        issue: '{{ store.target_switch_id }}'     
          